batch_size: 128
test_batch_size: 100
lr: 0.001
momentum: 0.9
decay: 0.0005
epochs: 302
save_on_epochs: []
optimizer: SGD
log_interval: 10

save_model: False
scheduler: True

resumed_model: model_image_Dec.09_10.46.38/model_last.pt.tar
#resumed_model: model_image_Aug.31_17.16.10/model_last.pt.tar


data: cifar

poisoning_proportion: 0.1
poison_number: 8
backdoor: True
alpha: 0.95
scale_threshold: 0.1

normalize: loss+

log: False
tb: False

random: False
gan: False
defense: True

losses:
  - backdoor
  - normal
#  - ewc
#  - latent
#  - latent_fixed

poison_images_test:
  - 330
  - 568
  - 3934
  - 12336
  - 30560
  - 30696
  - 33105
  - 33615
  - 33907
  - 36848
  - 40713
  - 41706

poison_images:
  - 330
  - 568
  - 3934
  - 12336
  - 30560
  - 30696
  - 33105
  - 33615
  - 33907
  - 36848
  - 40713
  - 41706