batch_size: 128
lr: 0.001
momentum: 0.9
decay: 0.0005
epochs: 400
save_on_epochs: []
optimizer: SGD
log_interval: 20

save_model: True
scheduler: True

resumed_model: model_image_Dec.09_10.46.38/model_last.pt.tar


data: cifar

poisoning_proportion: 0.01
poison_number: 8
backdoor: True
alpha: 0.95
scale_threshold: 0.1

normalize: loss+

log: True
tb: True

random: False


losses:
  - backdoor
  - normal
  - latent
#  - latent_fixed