batch_size: 128
lr: 0.001
momentum: 0.9
decay: 0.0005
epochs: 310
save_on_epochs: []
optimizer: SGD

log_interval: 50

data: image


save_model: False
scheduler: False

poisoning_proportion: 1
backdoor: True

log: False