batch_size: 128
test_batch_size: 100
lr: 0.1
momentum: 0.9
decay: 0.0005
epochs: 400
save_on_epochs: []
optimizer: SGD
log_interval: 10

save_model: True
scheduler: True

#resumed_model: model_image_Aug.15_11.40.44/model_last.pt.tar


data: cifar

poisoning_proportion: 1
poison_number: 8
backdoor: True
alpha: 0.95
scale_threshold: 0.1

normalize: loss+

log: True
tb: True

random: False


losses:
  - backdoor
  - normal
#  - ewc
  - latent
#  - latent_fixed